version: '3.9'

services:
  touitomamout:
    build:
      context: ./
    environment:
      - ENV_FILE=/data/.env
      - STORAGE_DIR=/data
      - DAEMON_PERIOD_MIN=1
    volumes:
      - ./data:/data