name: GitHub Release

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  # Handle the GitHub release creation only on "main" branch
  github-release:
    name: "Create GitHub release"
    runs-on: ubuntu-latest
    # Only run on "main" branch
    if: ${{ endsWith(github.ref, 'main') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create changelog
        id: changelog
        uses: loopwerk/tag-changelog@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config_file: .github/tag-changelog.cjs

      - name: Create release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changes }}
